feat: changed to typeorm
RockyHubJsc/example-nx-app pull request #1
Opened 2023-04-19 04:32 UTC by llong2195

2023-04-19 05:00 UTC, tuanbm requested changes

2023-04-19 05:00 UTC, tuanbm commented on apps/api/src/app/database/database.module.ts
> +      ): Promise<TypeOrmModuleOptions> => ({
Change to support mysql replication configuration

2023-04-19 07:08 UTC, tuanbm commented
```
Create migration: yarn typeorm:create apps/api/src/app/database/migrations/createTableUser
Run migration: typeorm:up
```
Change the create command to remove (not require) the absolute path, just the name.

2023-04-25 04:33 UTC, llong2195 commented
> ```
> Create migration: yarn typeorm:create apps/api/src/app/database/migrations/createTableUser
> Run migration: typeorm:up
> ```
> 
> Change the create command to remove (not require) the absolute path, just the name.

https://github.com/OnionStudios/example-nx-app/pull/5

2023-04-25 04:34 UTC, llong2195 commented
> > ```
> > Create migration: yarn typeorm:create apps/api/src/app/database/migrations/createTableUser
> > Run migration: typeorm:up
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Change the create command to remove (not require) the absolute path, just the name.
> 
> add #5

2023-05-16 05:21 UTC, merged